system:
  external:
    konfacc:
      url: https://acc-devel7-srv.altar.com.pl/adrianb-pc/konfacc/servicesrest
spring:
  datasource:
    url: jdbc:postgresql://192.168.14.50:5432/accdb
    username: konfacc
    password: konfacc
    platform: postgresql
    initialize: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        id:
          new_generator_mappings: false
        format_sql: true
        ddl-auto: none
