spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        id:
          new_generator_mappings: false
        format_sql: true
        ddl-auto: none
  datasource:
    username: konfacc
    password: konfacc
    platform: postgresql
    initialize: true
logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    pl.com.altar: INFO
    org.hibernate.SQL: INFO
  config: classpath:logback-spring.xml
  file: queue-offline-server
  path: logs
server:
  port: 8091
  tomcat:
    basedir: file:.
    accesslog:
      directory: logs
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: common
      prefix: access_log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
      suffix: .log
