system:
  external:
    konfacc:
      url: 
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/accdb
    username: konfacc
    password: konfacc
    platform: postgresql
    initialize: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        id:
          new_generator_mappings: false
        format_sql: true
        ddl-auto: none
